---
- name: Install required packages
  hosts: olimex_dev_boards
  gather_facts: yes
  become: true

  tasks:
    - name: Install build-essential
      apt:
        name: build-essential
        state: present
    
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install rustup
      become_user: olimex
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=1.67.1
      args:
        executable: /bin/bash
        creates: /home/olimex/.cargo/bin/rustup

    - name: Add Rust to PATH
      become_user: olimex
      lineinfile:
        dest: /home/olimex/.bashrc
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'
        state: present

    - name: Install pkg-config
      apt:
        name: pkg-config
        state: present

    - name: Install libmodbus-dev
      apt:
        name: libmodbus-dev
        state: present

    - name: Install autoconf
      apt:
        name: autoconf
        state: present

    - name: Install libtool
      apt:
        name: libtool
        state: present

    - name: Install clang
      apt:
        name: clang
        state: present

    - name: Install git
      apt:
        name: git
        state: present

    - name: Create GitHub folder
      become_user: olimex
      file:
        path: /home/olimex/github
        state: directory
        mode: '0755'

    - name: Check for existing repository
      become_user: olimex
      stat:
        path: /home/olimex/github/opensesame
      register: opensesame_folder_stat

    - name: Clone the repository
      become_user: olimex
      git:
        repo: https://github.com/ElektraInitiative/opensesame.git
        dest: /home/olimex/github/opensesame
        clone: yes
      when: not opensesame_folder_stat.stat.exists

